### ISSUE TITLE
Attempting to set className does not work as expected

### ISSUE THREAD

**Issue by Jonagent** [Lusito/tsx-dom#18]
Setting the prop `className` as per the type results in unexpected behavior.  
The property to set in this case is "class", eg:

```tsx
// TSX
<div className="myClass" />
```
would be equivalent to:
```html
// HTML
<div class="myClass" />
```

I notice React uses the `className` method as well, which makes sense as the types used in this project seem to be taken from React (Preact?).

I have made the change which I've been using in my project in [this fork](https://github.com/Lusito/tsx-dom/compare/master...Jonagent:tsx-dom:master).  I would have submitted a pull request but the tests fail even before I make any changes.

**Comment by Lusito** [comment]
The prop for class is actually class and not className in this project. You are probably writing JavaScript, as TypeScript would vave complained here.

React used className  because of a reason that is no longer valid. Afaik you can use class in react as well nowadays.

**Comment by Jonagent** [comment]
That is peculiar as the only reason I have the issue is due to TypeScript complaining.

![image](https://user-images.githubusercontent.com/19564798/224511812-aa064fbb-896f-4d49-9ac6-9345655fc1cd.png)

**Comment by Lusito** [comment]
Do you maybe have any other jsx/tsx libraries or types installed in your project? Maybe `@types/react`? DetailedHtmlProps does not come from my project
