### ISSUE TITLE
dangerouslySetInnerHTML does not function as expected

### ISSUE THREAD

**Issue by Jonagent** [Lusito/tsx-dom#19]
When using the `dangerouslySetInnerHTML` prop, it always sets the innerHTML to `[object Object]`.  

The type for `dangerouslySetInnerHTML` is:

```typescript
export interface HTMLComponentProps extends BaseProps {
    dangerouslySetInnerHTML?: { __html: string };
}
```

but the `setAttribute` file treats it as a string:
```typescript
if (name === "dangerouslySetInnerHTML") element.innerHTML = value as string;
```

The fix I found for this is a bit coercive so I'm not particularly happy about it.  I made a branch in my fork, but beware it did merge with my previous issue so that line can be ignored.  My branch/example can be found [here](https://github.com/Lusito/tsx-dom/compare/master...Jonagent:tsx-dom:dangerouslySetInnerHTML)

**Comment by Lusito** [comment]
I don't know where you are seeing that type definition, but it's not on this project.

On this project, it's a string. I never understood, why this had to be an object for react.

See https://github.com/Lusito/tsx-dom/blob/ca4a2c0edd6d9ae3c4afd2c332b134579b3f8dc3/packages/tsx-dom/src/types.ts#L14

**Comment by Jonagent** [comment]
That does appear to be correct so I'll figure out whats going on with my types then.  Thanks.


For posterity:

![image](https://user-images.githubusercontent.com/19564798/224511942-2725d853-ba33-4249-b5ef-61c08f950fc8.png)
