### ISSUE TITLE
Definition conflict with VUE VNode

### ISSUE THREAD

**Issue by cary-hu** [Lusito/tsx-dom#20]
Hi, I have used `tsx-dom` in my project, and also, I have import VUE.

When I build my project, error occured:
```
TS2322: Type '{ children: Element; class: string; }' is not assignable to type 'ElementAttrs<HTMLAttributes>'.
  Property 'children' does not exist on type 'ElementAttrs<HTMLAttributes>'.
```

Have you have any idea about this issue?

**Comment by Lusito** [comment]
Hey, sorry, this somehow slipped past me. I don't think there is a way to use multiple jsx/tsx libaries in the same project.

**Comment by cary-hu** [comment]
Fine, I will careful use that, hhhh
