### ISSUE TITLE
Feature request: Add reactive attributes

### ISSUE THREAD

**Issue by bmarotta** [Lusito/tsx-dom#26]
It would be nice if you could add attributes that when changed the value is reflected in the DOM. The precondition that the attribute being set is an object property. Example:

`<button live:disable={this.buttonDisabled} ></button>`

On could then overwrite the property setter to mirror the value to the DOM.

I'll be glad to help you on this task.

**Comment by Lusito** [comment]
Maybe an existing reactive framework is a better choice for the job. Keep in mind: This is not a reactive framework. Making it reactive might be overkill for this project. That being said, I am willing to hear you out.

Can you expand a bit on this? Not sure what exactly you are trying to achieve. If you want automatic binding, then the above syntax would not work, as the code behind the JSX will only receive the current value of this.buttonDisabled and not a reference that can be watched. It might be possible if buttonDisabled was not a boolean, but instead an object of sorts, but I'm not sure that is such a good idea.

What would be your usecase for it? And what is `this` in this case? A [custom element](https://lusito.github.io/tsx-dom/tsx-dom/custom-elements.html)?
Do you just want to make sure that changes to this.buttonDisabled will be automatically applied to the DOM element? Or vice versa?

**Comment by bmarotta** [comment]
Hi,

Not sure if it can be achieved with CustomElement (maybe yes). While writing the answer I see that the solution might be a little clunky because you need to pass also an object instance. I understand that your library is supposed to be static, but all tsx solutions (I found) are based on using virtual DOM (which I find overkill for 90% of the cases) and embedding overhead to the code. Adding it to your library would be lightweight and wouldn't require any additional library.

This is how it could look like. Of course, you are free to change the change the "live" prefix or the way it works.

Image you have a tsx element like this.

`<input type="text" live:instance={myObj} live:value="myProperty" />`

Please note that live:instance is an actual instance to an object (in curly brackets) and value is a string which points to an object property name.

Then in your code generator, you would have something like this (not tested pseudo code):

```javascript
// If the attribute starts with live, it is a live attribute
if (attribute.name.startsWith("live:")) {

  // Gets the real attribute that we are trying to set
  const realAttribute = attribute.split(".")[0];

  // If it is "instance", then this is the instance of the object we want to observe for this element
  if (realAttribute === "instance") {
    objectInstance = attribute.value;
  } else {
    // First set the attribute value to the object property value
    setAttribute(realAttribute, objectInstance[attribute[value]];

    // Check what kind of property it is
    const propertyDescriptor = Object.getOwnPropertyDescriptor(realAttribute);

    // If the property has a get and/or a set, it is already a "property". Create a new getter and setter overriding the 
    // existing ones. This is achieved by using the method Object.defineProperty
    // If it doesn't have a getter and setter, create one.
    // In the new setter we need to call the old setter plus update the element attribute
    ...
  }
}
```

And this is how an overrideSetter function could look like (not fully tested)

```typescript
overrideSetter(obj: Object, propertyName: string, newFunctionality: (value: any) => void) {
        const proto = Object.getPrototypeOf(obj);
        const originalDescriptor = Object.getOwnPropertyDescriptor(proto, propertyName);

        if (!originalDescriptor || !originalDescriptor.get || !originalDescriptor.set) {
            throw new Error(`Getter and Setter not found for property ${propertyName}`);
        }

        Object.defineProperty(obj, propertyName, {
            set: (value: number) => {
                // Call the original setter
                originalDescriptor.set!.call(obj, value);

                // Call the additional functionality
                try {
                    newFunctionality(originalDescriptor.get!.call(obj));
                } catch (ex) {
                    console.error(`Error calling new functionality for property ${propertyName} setter: ${ex}`);
                }
            },
            get: originalDescriptor.get,
            enumerable: true,
            configurable: true
        });
    }
```

**Comment by Lusito** [comment]
I'm sorry, but before I can try to understand your implementation idea, I really need to understand your use-case a bit more. What is it that you want to achieve with this?

I currently imagine your use-case to be like this:

```tsx
function MyComponent() {
  const instance = { value: "initial" };

  return (
    <div>
      <button onClick={() => instance.value = "changed"}>change value</button>
      <span live:istance={instance} live:textContent="value" />
    </div>
  );
}
```

So when you click the button, the instance will be changed and the span element as well.

However, this can be achieved like this as well and is easier to understand (in my opinion):
```tsx
function MyComponent() {
  const spanRef = createRef<HTMLSpanElement>();

  return (
    <div>
      <button onClick={() => (spanRef.textContent = "foo")}>change value</button>
      <span ref={spanRef}>initial</span>
    </div>
  );
}
```
Of course, this removes the need to the `instance` object. Not sure if that is something you need for something else.
As said, I'm not sure I understand your use-case correctly. So please expand on _what_ you want to achieve rather than _how_ you want to achieve it.

**Comment by Lusito** [comment]
> I understand that your library is supposed to be static

Just to clarify: tsx-dom-server is supposed to be static. With tsx-dom you can be as flexible as you like. You just have to work with the elements manually by storing references and manipulating them.

**Comment by bmarotta** [comment]
Of course it can be achieved in some other ways. At the end, everything tsx-dom does can also be achieved by writing pure DOM code ;) 

I just think it would be nice to have a little bit of intrinsic logic for things that happen very often like: 
 - Enabling/Disabling components
 - Showing/Hiding components
 - Changing component values based on the application behavior.
 
And to use React is overkill for simple applications.

Also in your example you think of the component being the end game (you refrain from having an object instance at all), while I was thinking about having the component as a mirror of the object. Another example:

```
class User {
  _name: string;
  _email: string;
  _age: number;
  _readonly: boolean;
  get name(): string {
    return _name;
  }
  set name(value: string) {
    // Do some validation here
    this._name = value;    
 }
 // ... getters and setters for email, age and readonly
}

function UserComponent(user: User) {
  <div>
    <input live:instance={user} live:value="name" live:readonly="readonly" />
    <input live:instance={user} live:value="email" live:readonly="readonly" />
    <input type="number" live:instance={user} live:value="age" live:readonly="readonly" />
  </div>
}
```

These are just silly theoretical examples, but I still think it would be a nice feature.

**Comment by Lusito** [comment]
Ok, I'm starting to get a picture of what you want. I see the following issues:
- Your code is very unclear to those who have not studied this special behavior.
- You can only specify one instance. What if you want one property from one object and another property from a different object, but on the same element?
- Adding listeners to these properties is probably possible, but what about removing listeners? I think all of this can get quite messy and cause memory leaks.
- This will only work for attributes. You will not be able to do this for children (for example a list of users)

The first issue can be overcome by adjusting the name a bit: bind instead of live, as that is a more commonly used term in other frameworks.

The second issue could be solved by writing it like this instead:
```tsx
function UserComponent(user: User) {
    return <div>
        <input value={bind(user, "name")} readonly={bind(user, "readonly")} />
        <input value={bind(user, "email")} readonly={bind(user, "readonly")} />
        <input type="number" value={bind(user, "age")} readonly={bind(user, "readonly")} />
    </div>
}
```

As for the other issues, I don't think they can be solved easily.

Btw, if size and speed are an issue for you with react, have you tried [svelte](https://svelte.dev/)? It creates a lot smaller bundles and I've heard good things about it too (though I didn't try it yet).

**Comment by Lusito** [comment]
Another issue: binding would only work on html/svg element attributes, not on function component properties, as the component function will only be called once.

**Comment by bmarotta** [comment]
Hi @Lusito,

Thanks for the insightful thoughts. Yes, I like the idea of bind, it is far better than live. For me it is pretty fine it only works with attributes. Actually I can implement the bind even without touching your library already. 

For the memory leak, I see 2 solutions. Either the library implement a [MutationObserver](https://stackoverflow.com/a/72303928) to listen for changes in the DOM (haven't tried it myself). But I think this problem is mostly overstated if you don't have a single page application.

Another problem is when more than 1 component is listening to a single object. Either you will have a cascade of setters or one needs to implement a kind of singleton which keeps a catalog of all objects and properties being listened.

Regarding Svelte, I heard about it. But since in the last 10 years I see frameworks coming and going all the time, I prefer to work as close to plain javascript standards as possible.

In any case, it was nice exchanging ideas with you. I assume that you don't want to implement such a feature, so I will just close the issue.

Cheers

**Comment by bmarotta** [comment]
That's great news. Because functional components should have never existed in the first place. It is another trade-off from React:  going 20 years in the past, writing verbose not-extendable cose for gaining some discussable performance improvement. 

On August 18, 2024 12:07:39 AM GMT+02:00, Lusito ***@***.***> wrote:
>Another issue: binding would only work on html/svg element attributes, not on function component properties, as the component function will only be called once.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Lusito/tsx-dom/issues/26#issuecomment-2294998780
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
