### ISSUE TITLE
onError callback missing

### ISSUE THREAD

**Issue by ChlodAlejandro** [Lusito/tsx-dom#3]
I just noticed that the `onError` callback for the elements were missing.

In the following block:
```jsx
<script
    type="application/javascript"
    onLoad={() => {
        alert("ok");
    }}
    onError={() => {
        alert("not ok");
    }}
    src={src} />
```
The following error appears for me:
```
TS2322: Type '{ type: string; onLoad: () => void; onError: () => void; src: string; }' is not assignable to type 'HTMLAttributes'.
   Property 'onError' does not exist on type 'HTMLAttributes'.
```
![image](https://user-images.githubusercontent.com/12129227/95670353-7f27bd00-0bbc-11eb-948f-e7c51a833782.png)

Is this a small oversight or was this intentional?

**Comment by Lusito** [comment]
Thanks for the report.

When I created this project, I took definitions from [preact](https://github.com/developit/preact). They have since updated their definitions and I've just merged these updates. Version 1.0.0 has been published with the missing attributes.

**Comment by ChlodAlejandro** [comment]
Ah, I see. Thanks a lot for the fix!
