### ISSUE TITLE
Nested array support

### ISSUE THREAD

**Issue by sportshead** [Lusito/tsx-dom#6]
Currently, trying to append an array using this syntax breaks for me:
```tsx
function SomeComponent({ children }: BaseProps): JSX.Element {
    return (
        <h2>
            {children}
        </h2>
    );
}

const myArray = [<h3>Hello World</h3>, <p>1+1=2</p>, <p>foo bar baz quux</p>];

document.body.appendChild(<SomeComponent>{...myArray}</SomeComponent>)
```

I get a warning saying something like `index.js?e931:17 Unknown type to append:  (3) [h3, p, p]`
It seems that `applyChildren` correctly identifies children as an array, and calls `applyChild`. On closer inspection, for some reason the `children` argument to `applyChildren` is a nested array: `[[h3, p, p]]`

A possible fix would be to call `applyChildren` from `applyChild`, making nested arrays possible.

**Comment by Lusito** [comment]
1.1.0 is released
