### ISSUE TITLE
svg element support!

### ISSUE THREAD

**Issue by PerryHuan9** [Lusito/tsx-dom#9]
Now, tsx-dom don't support  svg element.
![image](https://user-images.githubusercontent.com/31561213/115119593-cbc0da80-9fdb-11eb-8aa0-0a52d29cb3e4.png)

I advice that tsx-dom can support svg elements.

**Comment by Lusito** [comment]
Thanks for the report. Try version 1.3.0, I've added types for svg. I didn't get to extensively test it, but it should work I think.

**Comment by iamnafets** [comment]
@Lusito did you commit the code associated with version 1.3.0? The package in NPM seems out of date with the repo. Thanks for publishing this package! Very useful.

**Comment by Lusito** [comment]
@iamnafets You're right, I forgot to push the latest commit to the repository. The npm package itself is up to date though. I've just pushed the changes.
